// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:f68bc0fb-7d80-4481-a816-2f727ae7de4d",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_QD9wmX4S5",
    "aws_user_pools_web_client_id": "1dm7jtk3etbv8mqobvbiosrlga",
    "aws_mobile_analytics_app_id": "597739686247443ba9d6b90e516a11d0",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
